runtime: nodejs20
# runtime: nodejs
# env: flex

# runtime_config:
#   operating_system: "ubuntu22"

# network:
#   session_affinity: true

# manual_scaling:
#   instances: 1

# handlers:
#   - url: /.*
#     script: auto
#     secure: always

# resources:
#   memory_gb: 4
