services:
  tenpaisabackend:
    image: surajrimal/tenpaisabackend:latest
    container_name: tenpaisabackend
    restart: always
    ports:
      - "4000:4000"
      - "8081:8081"
    volumes:
      - ./public:/app/public
    env_file:
      - .env

networks:
  default:
    external: true
    name: nginx
