export class ApiStatus {
    static SUCCESS = 200;
    static CREATED = 201;
    static ACCEPTED = 202;
    static NO_CONTENT = 204;
    static BAD_REQUEST = 400;
    static UNAUTHORIZED = 401;
    static FORBIDDEN = 403;
    static NOT_FOUND = 404;
    static METHOD_NOT_ALLOWED = 405;
    static CONFLICT = 409;
    static INTERNAL_SERVER_ERROR = 500;
    static BAD_GATEWAY = 502;
    static SERVICE_UNAVAILABLE = 503;
    static GATEWAY_TIMEOUT = 504;
    static INVALID_INPUT = 422;
    static TOO_MANY_REQUESTS = 429;
    static TOKEN_MISSING = 498;
    static TOKEN_EXPIRED = 440;
  }