name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push multi-platform Docker image
      run: |
        docker buildx build \
          --platform linux/arm64 \
          -t docker.io/surajrimal/tenpaisabackend:latest \
          --push .

        # Notify via ntfy
        curl -X POST https://notifications.surajr.com.np \
          -H "Content-Type: application/json" \
          -d '{"title": "Docker Build Complete", "message": "Docker image surajrimal/tenpaisabackend:latest has been built and pushed successfully."}'

    - name: Notify Jenkins of new build
      run: |
        curl -X POST http://jenkins.surajr.com.np/generic-webhook-trigger/invoke/ \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ secrets.JENKINS_WEBHOOK_TOKEN }}" \
          -d '{"event": "docker_image_pushed", "repository": "docker.io/surajrimal/tenpaisabackend", "tag": "latest"}'

        # Notify via ntfy
        curl -X POST https://notifications.surajr.com.np \
          -H "Content-Type: application/json" \
          -d '{"title": "Jenkins Notification", "message": "Jenkins has been notified about the new Docker image build."}'